spring:
  application:
    name: Appointment-Service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: S1mpL0rd
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 8083